# ============================================================
# 12_publication_restyle_outputs.R
# Central publication-style pass for all manuscript outputs
# ============================================================
# Purpose:
#   - standardize figure typography without changing analyses
#   - standardize all main/supplementary table layouts
#   - use a continuous grey title/header area for every PNG table
#   - re-export existing output objects at publication resolution
#
# This script is intentionally sourced LAST by 00_master_run_all.R so it can
# restyle and overwrite presentation files generated by earlier scripts while
# leaving all statistical objects and estimates unchanged.

PUBLICATION_DPI <- 600
PUBLICATION_BASE_SIZE <- 11
PUBLICATION_TITLE_SIZE <- 12
PUBLICATION_SUBTITLE_SIZE <- 10
PUBLICATION_AXIS_TITLE_SIZE <- 11
PUBLICATION_AXIS_TEXT_SIZE <- 10
PUBLICATION_LEGEND_TITLE_SIZE <- 10
PUBLICATION_LEGEND_TEXT_SIZE <- 9
PUBLICATION_TABLE_BODY_SIZE <- 9
PUBLICATION_TABLE_TITLE_SIZE <- 11
PUBLICATION_TABLE_HEADER_BG <- "#E6E6E6"
PUBLICATION_TABLE_COLUMN_BG <- "#F2F2F2"
PUBLICATION_TABLE_SECTION_BG <- "#F7F7F7"

# ------------------------------------------------------------
# Figures: one typography layer, preserving plot-specific geometry/grid
# ------------------------------------------------------------
publication_theme_override <- ggplot2::theme(
  plot.title = ggplot2::element_text(
    face = "bold",
    hjust = 0.5,
    size = PUBLICATION_TITLE_SIZE,
    margin = ggplot2::margin(b = 8)
  ),
  plot.subtitle = ggplot2::element_text(
    hjust = 0.5,
    size = PUBLICATION_SUBTITLE_SIZE,
    margin = ggplot2::margin(b = 8)
  ),
  axis.title = ggplot2::element_text(size = PUBLICATION_AXIS_TITLE_SIZE),
  axis.text = ggplot2::element_text(size = PUBLICATION_AXIS_TEXT_SIZE),
  legend.title = ggplot2::element_text(size = PUBLICATION_LEGEND_TITLE_SIZE),
  legend.text = ggplot2::element_text(size = PUBLICATION_LEGEND_TEXT_SIZE),
  strip.text = ggplot2::element_text(size = 10, face = "bold"),
  plot.margin = ggplot2::margin(t = 18, r = 28, b = 18, l = 28, unit = "pt")
)

publicationize_plot <- function(plot) {
  plot + publication_theme_override
}

save_publication_plot <- function(plot,
                                  filename,
                                  folder,
                                  width,
                                  height,
                                  dpi = PUBLICATION_DPI) {
  dir.create(folder, recursive = TRUE, showWarnings = FALSE)
  ggplot2::ggsave(
    filename = file.path(folder, filename),
    plot = plot,
    width = width,
    height = height,
    dpi = dpi,
    bg = "white",
    limitsize = FALSE
  )
}

# Figure 1 is a flowchart rather than an x/y data display. Keep it inside the
# central publication styling pass, but suppress all axes explicitly so the
# global figure typography does not re-introduce technical x/y scales.
if (exists("figure_1_study_flowchart", inherits = TRUE)) {
  figure_1_flowchart_publication <- figure_1_study_flowchart +
    ggplot2::labs(x = NULL, y = NULL) +
    ggplot2::theme_void() +
    ggplot2::theme(
      plot.title = ggplot2::element_text(
        face = "bold",
        hjust = 0.5,
        size = PUBLICATION_TITLE_SIZE,
        margin = ggplot2::margin(b = 8)
      ),
      plot.margin = ggplot2::margin(
        t = 18, r = 28, b = 18, l = 28,
        unit = "pt"
      )
    )

  save_publication_plot(
    figure_1_flowchart_publication,
    filename = "Figure_1_Study_Flowchart.png",
    folder = file.path("outputs", "figures"),
    width = 7,
    height = 6
  )
}

# All remaining ggplot figures retain the existing global publication override.
figure_specs <- list(
  list("figure_2_weightloss_distribution", "Figure_2_Weightloss_Distribution.png", "figures", 7, 5),
  list("figure_3_weightloss_by_feeding", "Figure_3_Weightloss_By_Feeding.png", "figures", 7, 5),
  list("appendix_figure_s1_subgroup_forest", "Supplementary_Figure_S1_Breastfeeding_Subgroups.png", "appendix_figures", 12, 7),
  list("appendix_figure_s2_historical_exposures", "Supplementary_Figure_S2_Historical_Exposures.png", "appendix_figures", 14, 7.5),
  list("appendix_figure_s3_sensitivity_forestplot", "Supplementary_Figure_S3_Sensitivity_Forestplot.png", "appendix_figures", 14, 7.5),
  list("appendix_figure_s4_excessive_weightloss", "Supplementary_Figure_S4_Excessive_Weightloss_By_Feeding.png", "appendix_figures", 12, 7),
  list("appendix_figure_s5_weightloss_by_year", "Supplementary_Figure_S5_Weightloss_By_Year.png", "appendix_figures", 8, 5),
  list("appendix_figure_s6_feeding_by_year", "Supplementary_Figure_S6_Feeding_By_Birthyear.png", "appendix_figures", 8, 5),
  list("supplementary_figure_s7_measurement_timing", "Supplementary_Figure_S7_Weight_Measurement_Timing.png", "appendix_figures", 9, 7)
)

for (spec in figure_specs) {
  object_name <- spec[[1]]
  if (!exists(object_name, inherits = TRUE)) {
    warning("Publication restyle skipped missing figure object: ", object_name)
    next
  }
  save_publication_plot(
    publicationize_plot(get(object_name, inherits = TRUE)),
    filename = spec[[2]],
    folder = file.path("outputs", spec[[3]]),
    width = spec[[4]],
    height = spec[[5]]
  )
}

# Figure 4 is a patchwork object with panel-specific x-axis labels. Rebuild it
# from the reviewer-update panels so the separate beta/OR axes are retained,
# while the figure-level typography matches every other figure.
if (exists("figure_4_panel_linear", inherits = TRUE) &&
    exists("figure_4_panel_logistic", inherits = TRUE) &&
    requireNamespace("patchwork", quietly = TRUE)) {

  publication_figure4_panel_theme <- ggplot2::theme(
    plot.title = ggplot2::element_text(
      face = "bold", hjust = 0, size = 11,
      margin = ggplot2::margin(b = 8)
    ),
    axis.title.x = ggplot2::element_text(
      size = PUBLICATION_AXIS_TITLE_SIZE,
      margin = ggplot2::margin(t = 7)
    ),
    axis.text.x = ggplot2::element_text(size = PUBLICATION_AXIS_TEXT_SIZE),
    axis.text.y = ggplot2::element_text(size = PUBLICATION_AXIS_TEXT_SIZE)
  )

  figure_4_panel_linear_publication <-
    figure_4_panel_linear + publication_figure4_panel_theme

  figure_4_panel_logistic_publication <-
    figure_4_panel_logistic + publication_figure4_panel_theme +
    ggplot2::theme(
      axis.text.y = ggplot2::element_blank(),
      axis.ticks.y = ggplot2::element_blank(),
      axis.line.y = ggplot2::element_blank()
    )

  figure_4_adjusted_forest <- patchwork::wrap_plots(
    figure_4_panel_linear_publication,
    figure_4_panel_logistic_publication,
    nrow = 1,
    widths = c(1.35, 1)
  ) +
    patchwork::plot_annotation(
      title = "Figure 4. Adjusted associations with neonatal weight loss",
      subtitle = "Gestational-age-adjusted main models",
      theme = ggplot2::theme(
        plot.title = ggplot2::element_text(
          face = "bold",
          hjust = 0.5,
          size = PUBLICATION_TITLE_SIZE,
          margin = ggplot2::margin(b = 4)
        ),
        plot.subtitle = ggplot2::element_text(
          hjust = 0.5,
          size = PUBLICATION_SUBTITLE_SIZE,
          margin = ggplot2::margin(b = 8)
        ),
        plot.margin = ggplot2::margin(t = 8, r = 10, b = 6, l = 10, unit = "pt")
      )
    )

  save_publication_plot(
    figure_4_adjusted_forest,
    filename = "Figure_4_Adjusted_Associations_Forestplot.png",
    folder = file.path("outputs", "figures"),
    width = 11.2,
    height = 6.5
  )
}

# ------------------------------------------------------------
# Tables: one GT style for main and supplementary tables
# ------------------------------------------------------------
build_publication_gt <- function(data,
                                 title,
                                 groupname_col = NULL,
                                 highlight_sections = FALSE,
                                 font_size = PUBLICATION_TABLE_BODY_SIZE) {
  if (is.null(groupname_col)) {
    tbl <- gt::gt(data)
    visible_columns <- names(data)
  } else {
    tbl <- gt::gt(data, groupname_col = groupname_col)
    visible_columns <- setdiff(names(data), groupname_col)
  }

  tbl <- tbl %>%
    gt::tab_header(title = title) %>%
    gt::tab_options(
      table.font.size = gt::px(font_size),
      heading.title.font.size = gt::px(PUBLICATION_TABLE_TITLE_SIZE),
      heading.title.font.weight = "bold",
      heading.align = "left",
      heading.padding = gt::px(8),
      heading.background.color = PUBLICATION_TABLE_HEADER_BG,
      table.width = gt::pct(100),
      table.background.color = "white",
      data_row.padding = gt::px(4),
      column_labels.padding = gt::px(6),
      column_labels.font.weight = "bold",
      column_labels.background.color = PUBLICATION_TABLE_COLUMN_BG,
      table.border.top.width = gt::px(1.2),
      table.border.bottom.width = gt::px(1.2),
      table.border.top.color = "#222222",
      table.border.bottom.color = "#222222",
      heading.border.bottom.width = gt::px(0),
      column_labels.border.top.width = gt::px(0),
      column_labels.border.bottom.width = gt::px(1),
      column_labels.border.bottom.color = "#555555",
      row_group.font.weight = "bold",
      row_group.background.color = PUBLICATION_TABLE_SECTION_BG,
      row_group.padding = gt::px(5),
      source_notes.font.size = gt::px(8)
    ) %>%
    gt::tab_style(
      style = gt::cell_borders(
        sides = "bottom",
        color = "#E5E5E5",
        weight = gt::px(0.5)
      ),
      locations = gt::cells_body()
    )

  if (length(visible_columns) >= 1) {
    tbl <- tbl %>%
      gt::cols_align(align = "left", columns = dplyr::all_of(visible_columns[1]))
  }
  if (length(visible_columns) >= 2) {
    tbl <- tbl %>%
      gt::cols_align(align = "center", columns = dplyr::all_of(visible_columns[-1]))
  }

  if (highlight_sections && "Characteristic" %in% visible_columns) {
    main_section_rows <- c(
      "Continuous characteristics",
      "Categorical characteristics",
      "Outcome"
    )
    subsection_rows <- c(
      "Parity",
      "Historical exposures",
      "Neonatal characteristics",
      "Feeding characteristics"
    )

    tbl <- tbl %>%
      gt::tab_style(
        style = list(
          gt::cell_text(weight = "bold"),
          gt::cell_fill(color = PUBLICATION_TABLE_SECTION_BG)
        ),
        locations = gt::cells_body(
          columns = dplyr::any_of(c("Characteristic", "Value")),
          rows = Characteristic %in% main_section_rows
        )
      ) %>%
      gt::tab_style(
        style = gt::cell_text(weight = "bold", style = "italic"),
        locations = gt::cells_body(
          columns = Characteristic,
          rows = Characteristic %in% subsection_rows
        )
      )
  }

  tbl
}

save_publication_table <- function(data,
                                   title,
                                   filename,
                                   folder,
                                   width,
                                   height,
                                   groupname_col = NULL,
                                   highlight_sections = FALSE,
                                   font_size = PUBLICATION_TABLE_BODY_SIZE) {
  dir.create(folder, recursive = TRUE, showWarnings = FALSE)

  tbl <- build_publication_gt(
    data = data,
    title = title,
    groupname_col = groupname_col,
    highlight_sections = highlight_sections,
    font_size = font_size
  )

  gt::gtsave(
    data = tbl,
    filename = file.path(folder, filename),
    vwidth = width,
    vheight = height,
    expand = 20
  )

  invisible(tbl)
}

# Main tables
if (exists("table_1_population", inherits = TRUE)) {
  save_publication_table(
    table_1_population,
    "Table 1. Characteristics of the analytical study population",
    "Table_1_Cohort_Characteristics.png",
    file.path("outputs", "tables_png"),
    width = 1200, height = 1200,
    highlight_sections = TRUE
  )
}

if (exists("table_MX_linear_period_GA_clean", inherits = TRUE)) {
  save_publication_table(
    round_numeric_df(table_MX_linear_period_GA_clean),
    "Table 2. Linear regression: maximum neonatal weight loss, gestational-age-adjusted main model",
    "Table_2_Linear_GA_Main.png",
    file.path("outputs", "tables_png"),
    width = 1400, height = 1100
  )
}

if (exists("table_MX_logistic_period_GA_clean", inherits = TRUE)) {
  save_publication_table(
    round_numeric_df(table_MX_logistic_period_GA_clean),
    "Table 3. Logistic regression: high neonatal weight loss >10%, gestational-age-adjusted main model",
    "Table_3_Logistic_GA_Main.png",
    file.path("outputs", "tables_png"),
    width = 1400, height = 1100
  )
}

# Supplementary tables S1-S10
supplementary_table_specs <- list(
  list("Supplementary_Table_S7_Excluded_vs_Included",
       "Supplementary Table S1. Characteristics of included infants and infants excluded because of non-evaluable neonatal weight trajectories",
       "Supplementary_Table_S1_Excluded_vs_Included.png", 1500, 1200, NULL, TRUE, 9),
  list("table_6_feeding_allocation",
       "Supplementary Table S2. Maternal and neonatal characteristics according to feeding mode",
       "Supplementary_Table_S2_Feeding_Allocation.png", 1500, 1250, NULL, FALSE, 9),
  list("appendix_table_S3_direct_flu_GA",
       "Supplementary Table S3. Direct maternal influenza model, gestational-age-adjusted",
       "Supplementary_Table_S3_Direct_Maternal_Flu_GA.png", 1450, 1100, NULL, FALSE, 9),
  list("appendix_table_S4_flu_in_pregn_and_pandemic_GA",
       "Supplementary Table S4. Influenza in pregnancy during pandemic model, gestational-age-adjusted",
       "Supplementary_Table_S4_Flu_Pregnancy_Pandemic_GA.png", 1450, 1100, NULL, FALSE, 9),
  list("table_MX_linear_period_BW",
       "Supplementary Table S5. Birthweight-adjusted sensitivity analysis: maximum neonatal weight loss",
       "Supplementary_Table_S5_BW_Linear_Supplementary.png", 1450, 1100, NULL, FALSE, 9),
  list("table_MX_logistic_period_BW",
       "Supplementary Table S6. Birthweight-adjusted sensitivity analysis: high neonatal weight loss >10%",
       "Supplementary_Table_S6_BW_Logistic_Supplementary.png", 1450, 1100, NULL, FALSE, 9),
  list("Supplementary_Table_S6_Subgroup_Analyses",
       "Supplementary Table S7. Stratified breastfeeding subgroup analyses with Cochran-Q heterogeneity tests",
       "Supplementary_Table_S7_Subgroup_Analyses.png", 1600, 1500, NULL, FALSE, 9),
  list("supplementary_table_s8_measurement_completeness",
       "Supplementary Table S8. Maternal and neonatal characteristics according to availability of one versus two postnatal weight measurements",
       "Supplementary_Table_S8_One_vs_Two_Weight_Measurements.png", 1650, 1200, NULL, FALSE, 9),
  list("supplementary_table_s9_exact_vs_other",
       "Supplementary Table S9. Maternal and neonatal characteristics of infants with postnatal weights measured exactly on days 5 and 10 versus all other measurement patterns",
       "Supplementary_Table_S9_Exact_Day5_Day10_vs_Other_Patterns.png", 1800, 1250, NULL, FALSE, 9),
  list("supplementary_table_s10_exact_day_sensitivity",
       "Supplementary Table S10. Sensitivity analysis restricted to infants with postnatal weights measured exactly on days 5 and 10",
       "Supplementary_Table_S10_Exact_Day5_Day10_Sensitivity.png", 1900, 1650, "Outcome", FALSE, 8)
)

for (spec in supplementary_table_specs) {
  object_name <- spec[[1]]
  if (!exists(object_name, inherits = TRUE)) {
    warning("Publication restyle skipped missing table object: ", object_name)
    next
  }

  save_publication_table(
    data = round_numeric_df(get(object_name, inherits = TRUE)),
    title = spec[[2]],
    filename = spec[[3]],
    folder = file.path("outputs", "appendix_tables"),
    width = spec[[4]],
    height = spec[[5]],
    groupname_col = spec[[6]],
    highlight_sections = spec[[7]],
    font_size = spec[[8]]
  )
}

message(
  "Publication styling pass complete: figures and Tables S1-S10 were re-exported with unified typography and table headers."
)
